# === Binaries -----------------------------------------------------------------
#
BINS     += self_play
BINS     += train
BINS     += play

# === Shared Source Objects ----------------------------------------------------
#
SRC_OBJS += ${BUILD_OBJS}/game.o
SRC_OBJS += ${BUILD_OBJS}/mcts.o
SRC_OBJS += ${BUILD_OBJS}/nn.o
SRC_OBJS += ${BUILD_OBJS}/log.o

include mk.tpl
