name: 'z-action'
# check software versions
#
#     https://github.com/actions/runner-images
description: 'Common Action'
inputs:
  checkout_y:
    default: false
  require_clang:
    default: false
  clang_version:
    default: 15
  require_gcc:
    default: false
  gcc_version:
    default: 14
runs:
  using: "composite"
  steps:
    - name: Checkout y
      if: ${{ inputs.checkout_y == 'true' }}
      uses: actions/checkout@v4
      with:
        repository: xiejw/y
        path: y

    # === --- GCC related ------------------------------------------------ ===
    #
    - name: Set environmental variables for GCC
      if: ${{ inputs.require_gcc == 'true' }}
      shell: bash
      run: |
        echo "CC=gcc-${{ inputs.gcc_version }}" >> $GITHUB_ENV
        echo "CXX=g++-${{ inputs.gcc_version }}" >> $GITHUB_ENV
    - name: Install GCC
      if: ${{ inputs.require_gcc == 'true' }}
      shell: bash
      run: sudo apt-get install -y --no-install-recommends g++-${{ inputs.gcc_version }}
    - name: Display GCC version
      if: ${{ inputs.require_gcc == 'true' }}
      shell: bash
      run: ${CC} --version

    # === --- Clang related ------------------------------------------------ ===
    #
    # https://brandur.org/fragments/github-actions-env-vars-in-env-vars
    - name: Set environmental variables for Clang
      if: ${{ inputs.require_clang == 'true' }}
      shell: bash
      run: |
        echo "CC=clang-${{ inputs.clang_version }}" >> $GITHUB_ENV
        echo "CXX=clang++-${{ inputs.clang_version }}" >> $GITHUB_ENV
    - name: Install LLVM and Clang
      if: ${{ inputs.require_clang == 'true' }}
      shell: bash
      run: sudo apt-get install -y --no-install-recommends clang-${{ inputs.clang_version }} lld-${{ inputs.clang_version }}
    - name: Display Clang version
      if: ${{ inputs.require_clang == 'true' }}
      shell: bash
      run: ${CC} --version


