name: 'z-action'
# check software versions
#
#     https://github.com/actions/runner-images
description: 'Common Action'
inputs:
  require_clang:
    default: false
  clang_version:
    default: 15
runs:
  using: "composite"
  steps:
    # --------------------------------------------------------------------------
    # Clang related
    #
    # https://brandur.org/fragments/github-actions-env-vars-in-env-vars
    - name: Set environmental variables for Clang
      if: ${{ inputs.require_clang == 'true' }}
      shell: bash
      run: |
        echo "CC=clang-${{ inputs.clang_version }}" >> $GITHUB_ENV
        echo "CXX=clang++-${{ inputs.clang_version }}" >> $GITHUB_ENV
    - name: Install LLVM and Clang
      if: ${{ inputs.require_clang == 'true' }}
      shell: bash
      run: sudo apt-get install -y --no-install-recommends clang-${{ inputs.clang_version }} lld-${{ inputs.clang_version }}
    - name: Display Clang version
      if: ${{ inputs.require_clang == 'true' }}
      shell: bash
      run: ${CC} --version


