compile:
	make -C v4_horn  compile
	make -C v4_dlink compile

test:
	make -C v4_horn  test
	make -C v4_dlink test

fmt:
	make -C v4_horn  fmt
	make -C v4_dlink fmt

clean:
	make -C v4_horn  clean
	make -C v4_dlink clean

release:
	make -C v4_horn  release
	make -C v4_dlink release
