name: c4
run-name: ${{ github.actor }} is running tests for ${{ github.workflow }}
on: [push]
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout z
        uses: actions/checkout@v4
        with:
          path: z
      - uses: ./z/.github/actions/base

      # === --- Set up Python ---------------------------------------------- ===
      #
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # === --- Set up Python ---------------------------------------------- ===
      #
      - working-directory: ${{ github.workspace }}/z/${{ github.workflow }}
        run:  |
          C4_SANITY_CHECK=1 ./run.sh
