name: g5
run-name: ${{ github.actor }} is running tests for ${{ github.workflow }}
on: [push]
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout z
        uses: actions/checkout@v4
        with:
          path: z
      - uses: ./z/.github/actions/base
        with:
          require_go: true

      # ------------------------------------------------------------------------
      # set up Python
      #
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - working-directory: ${{ github.workspace }}/z/${{ github.workflow }}
        run:  |
          pip install torch --index-url https://download.pytorch.org/whl/cpu
          pip install numpy setuptools
          python py/sm.py
          python configure.py --model_dir /tmp

      # ------------------------------------------------------------------------
      # workflow
      #
      - name: Run ${{ github.workflow }} Test
        run: make -C ${{ github.workspace }}/z/${{ github.workflow }} clean test
      - name: Run ${{ github.workflow }} Release
        run: make -C ${{ github.workspace }}/z/${{ github.workflow }} release

      # ------------------------------------------------------------------------
      # cc
      #
      - name: Run ${{ github.workflow }} CC
        run: make -C ${{ github.workspace }}/z/${{ github.workflow }}/cc run

      # ------------------------------------------------------------------------
      # game
      #
      - name: Run ${{ github.workflow }} Game
        run: make -C ${{ github.workspace }}/z/${{ github.workflow }}/ game

